topic: |
  [场景] 与${peer_name}进行符合自己性格与背景的聊天
  [目标] 日常闲聊，自然轻松
  [要求] 
      交流大概5-8句话，然后自然的结束话题。
      不必一定回复每句话。
  [规则]
  每段对话由两部分组成：(请严格遵守格式输出)
  - 对话元信息：描述本次对话的状态。
  - 对话内容：描述本次对话的内容。

  [example]
  ```对话元信息
  - <心情>:(愉悦、悲伤，愤怒，恐惧，惊讶，平静)
  - <态度>:(友好、热情、冷淡、中性、恶劣)
  - <心里活动>
  - <指示符号>
  ```
  <内容>

  [对话元信息]
  正常对话指示符号为[NONE]
  一方想连续说话则指示符号输出[CONTINUE]
  看见对方输出[CONTINUE]后，如果不打算打断则输出[SKIP],打断则输出[BREAK]。
  如果一方说完话，另一方无语则另一方输出[PASS]
  结束话题使用[END]符号结尾。

  [对方信息]
  ${peer_info}

  接下来直接开始对话。
