topic: |
    # 事件：社交对话
        - 时间：现在正在发生
        - 地点：街道上相遇
        - 社交关系：朋友(${name},${peer_name})
        - 对方信息：$peer_info

    [注意] 
        非常随意的日常对话，闲聊,简洁，完整，动作和对话使用不同标记，不要发散太多。限制在本场景内，场景改变对话要结束。

    [结束条件]  
        结束对话时，必须双方都输出[END]符号。 如果一方结束，无更多话可说，一方尚未结束，那么结束方则使用[无更多信息][END]符号替代。"""